# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'V2FogCloud' do
pod 'AFNetworking'
pod 'SVProgressHUD'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for V2FogCloud

end
